### PR TITLE
feat: add readUtf8 and writeUtf8

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
@windwp is that what you need?

**Comment by targos** [comment]
@stropitek @maasencioh  what do you think?

**Comment by maasencioh** [comment]
LGTM if you already test the utf8 library

**Comment by targos** [comment]
Thanks. Merged and released in v3.2.0

**Comment by targos** [comment]
> Maybe it would make sense to also implement a readUtf8Char that is smart about the number of byte it reads.

Yeah, I don't know of a library that can do that. We should do it only if we know about a format that specifies the number of characters to read instead of the number of bytes.

**Pull request merged**
